# Generated by Django 4.0.6 on 2022-07-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MonthlyCosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveSmallIntegerField()),
                ("year", models.PositiveSmallIntegerField()),
                ("total", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name_plural": "MonthlyCosts",
                "ordering": ["-year", "-month"],
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("cost", models.PositiveIntegerField()),
                ("date", models.DateField(db_index=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
