# Generated by Django 4.0.6 on 2022-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycosts',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
