# Generated by Django 4.0.6 on 2022-07-31 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 7, 31, 13, 13, 7, 934357, tzinfo=utc))),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
